# Time: 2019/9/9  17:00
# Author jzh
# File constants.py

# 配置文件环境变量名

GLOBAL_SETTING_ENV_MAIL_USERNAME = 'MAIL_USERNAME'

GLOBAL_SETTING_ENV_MAIL_PASSWORD = 'MAIL_PASSWORD'

GLOBAL_SETTING_ENV_MAIL_SENDER = 'MAIL_SENDER'
